#All entries in ${CURLY_BRACES} should be set as ENV variables, for security reasons.
frontend:
  root:
    url: ${FRONTEND_ROOT_URL} #replace with valid URL
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  error:
    include-stacktrace: never
    include-message: always
  port: ${PORT}
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 10800s #3hours
        name: WD_SESSION
        same-site: lax
        secure: true
spring:
  datasource:
    password: ${MYSQL_PASSWORD}
    url: ${MYSQL_HOST}
    username: ${MYSQL_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch-size: 20
  cache:
    type: redis
    redis:
      time-to-live: PT30M #30minutes
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  session:
    store-type: redis
    redis:
      cleanup-cron: 0 1 * * * *
