frontend:
  server:
    url: http://localhost:8080 #replace with your frontend root URL here
logging:
  level:
    org:
      hibernate:
        SQL: debug
server:
  error:
    include-stacktrace: never
  port: 9000
  servlet:
    session:
      cookie:
        http-only: true
        max-age: 10800s #3hours
        name: WEDEMY
spring:
  datasource:
    password: ${DB_PASSWORD}
    url: ${DB_HOST}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch-size: 30
  cache:
    type: redis
    redis:
      time-to-live: PT30M #30minutes
  redis:
    host: localhost
    port: 6379
    password: ""
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
  session:
    store-type: redis
    redis:
      cleanup-cron: 0 1 * * * *
